export const FULL_NAME = 'Moch Dhandy Friyadi';
export const JOB_ROLE = 'Full Stack Engineer';
export const ROLE_OVERVIEW = 'I build robust and dynamic website application.';
export const ABOUT = 'Passionate Fullstack Developer with over 2 years of experience building end-to-end web applications, and over 2 years of dedicated Frontend development expertise. Proficient in PHP (Laravel), Vue.js, RESTful API integration, creating responsive, and user-friendly interfaces. Adept at working in Agile environments, collaborating with cross-functional teams, and delivering clean, maintainable code. Committed to continuous learning and adopting new technologies.';
export const EXPERIENCES = [
	{
		id: 'exp-1',
		period: 'Jun 2023 - Present',
		position: 'Full Stack Developer',
		company: 'PT Ordivo Teknologi Indonesia',
		job_desc: 'Developed and launched the Top-up feature, increasing transaction efficiency and contributing to a significant boost in user engagement and revenue.',
		tech_stack: [
			'JavaScript',
			'Vue',
			'PHP',
			'Laravel',
			'Go',
			'Restful API',
			'SQS',
			'Lambda',
			'Git',
			'Bootstrap 4',
			'HTML',
			'CSS',
			'SCSS',
		],
	},
	{
		id: 'exp-2',
		period: 'Mar - Oct 2023',
		position: 'Frontend Developer',
		company: 'PT Sapta Muda Berkarya',
		job_desc: 'Developed and launched the Top-up feature, increasing transaction efficiency and contributing to a significant boost in user engagement and revenue.',
		tech_stack: [
			'JavaScript',
			'Vue',
			'React',
			'Restful API',
			'Git',
			'HTML',
			'CSS',
		],
	},
	{
		id: 'exp-3',
		period: 'Feb 2021 - Jan 2023',
		position: 'Frontend Developer',
		company: 'PT Lawencon International',
		job_desc: 'Developed and launched the Top-up feature, increasing transaction efficiency and contributing to a significant boost in user engagement and revenue.',
		tech_stack: [
			'JavaScript',
			'Vue',
			'gRPC',
			'Git',
			'HTML',
			'CSS',
		],
	},
	{
		id: 'exp-4',
		period: 'Nov 2019 - May 2020',
		position: 'Frontend Developer',
		company: 'PT. Dtech Solusi Bisnis',
		job_desc: 'Developed and launched the Top-up feature, increasing transaction efficiency and contributing to a significant boost in user engagement and revenue.',
		tech_stack: [
			'JavaScript',
			'Vue',
			'Restful API',
			'Git',
			'HTML',
			'CSS',
		],
	},
	{
		id: 'exp-5',
		period: 'Jul - Nov 2019',
		position: 'Full Stack Developer',
		company: 'PT Kong Teknologi Asia',
		job_desc: 'Developed and launched the Top-up feature, increasing transaction efficiency and contributing to a significant boost in user engagement and revenue.',
		tech_stack: [
			'JavaScript',
			'Vue',
			'PHP',
			'Laravel',
			'Restful API',
			'Git',
			'HTML',
			'CSS',
		],
	},
]
